### ISSUE TITLE
[Plasma 5] Autostarted session of Cantata gets killed upon Alt + F4.

### ISSUE THREAD

**Issue by smirkybg** [CDrummond/cantata#759]
The expected behavior of Cantata when hitting the "X" or using Alt + F4 is to get minimized to tray in Plasma 5.
This functionality works only if you manually started Cantata.
If it's started by the Plasma 5 autostart, then once you close the Cantata (expecting it to minimize), it gets killed.

**Comment by CDrummond** [comment]
Is this a KDE build, Qt4, or Qt5 build? Cantata 1.5.2 or master?

Have you tried other apps? e.g. Clementine?

**Comment by Thaodan** [comment]
I use the Qt5 build and have the exact same behaviour. Minimize to tray to don't works here.

**Comment by smirkybg** [comment]
It's a Qt5 build:
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cantata

The version is 1.5.2.

**Comment by CDrummond** [comment]
Please try a Qt4 build, Qt5 seems to have a few issues with the system tray. For instance, under Unity the tray icon appears in the wrong location!

I might just disable system tray for Qt5...

**Comment by Thaodan** [comment]
Qt4 has a plugin which translates the xembed systray to the new statusnotifer tray, so this should be no issue or not?

**Comment by CDrummond** [comment]
Yeah, I think ubuntu patches it for the new status notifier item class.

Still, if a Qt4 build does not have the issue - then the issue is with Qt5. As the code in Catata is the *same* for Qt4 and Qt5.

**Comment by CDrummond** [comment]
Any updates on this? Can someone please try a Qt4 build.

**Comment by smirkybg** [comment]
Qt4 and Qt5 builds behave the same for me:

Qt4: https://www.youtube.com/watch?v=ZGNGo-Odtlw
Qt5: https://www.youtube.com/watch?v=R9NQwJ_s8VYOdtlw

On autostart, as you see, there's a process of cantata spawned.
After you close it with hitting the "X" or Alt+F4, Cantata gets killed.
After you launch Cantata manually, the default and expected behaviour of minimization takes place.
In the Qt4 build, you'll see a second Cantata tray icon, which is missing in the Qt5 demo.
Don't worry, it's still there, it's just marked as "Auto" in the tray.

**Comment by CDrummond** [comment]
Can you try Clementine, and VLC? Do these have similar issues?

**Comment by CDrummond** [comment]
Actually just tried with Clementine - and it works as expected. Odd thing is that if I have both Cantata and Clementine configured this way, and both restart on login, then Cantata also works. Something odd is going on. I'll have to add some debug and see what's going wrong.

**Comment by CDrummond** [comment]
Should be fixed in master now - can you please update and confirm that it is fixed for you?

Cantata as checking if the system tray was available before creating the icon. Looks like with Plasma that Cantata is autostarted before the system tray is - hence no icon.

**Comment by smirkybg** [comment]
Works perfectly.

**Comment by CDrummond** [comment]
Thanks for the confirmation, and sorry for taking so long with the fix.

**Comment by smirkybg** [comment]
No need for apologies, great work! :)

**Comment by Thaodan** [comment]
the problem is not really fixed, I don't why but cantata uses an old xemebed icon.
Usally Qt5 should use automaticly an status notifer icon but why it don't?
